platform :ios, '9.0'

target 'Scribe' do

  use_frameworks!

  # Pods for Scribe
pod 'RealmSwift', '~> 4.3.0'
pod 'TesseractOCRiOS'
pod 'CropViewController'
pod 'Eureka'
pod "PromiseKit", "~> 6.8"

end
